### ISSUE TITLE
Adding a new item in NewListingActivity creates a few errors tbh

### ISSUE THREAD

**Issue by elmtree8** [CMPUT301W16T16/GlamorousBorrowingWhaleApp#13]
1. If you then go back to the homepage or longClick to edit something and return to the My Items page some items are shown twice for some reason? Some aren't shown at all? Don't really know what's going on here?
2. Sometimes sizes don't show when you longClick an item? Pretty sure size only shows for the last item

**Comment by andrewpaquette** [comment]
this doesn't happen anymore after i messed with it a bit, go me
