### ISSUE TITLE
Random crash with NetworkChangeReciever

### ISSUE THREAD

**Issue by AdamGualberta** [CMPUT301W16T16/GlamorousBorrowingWhaleApp#16]
Unsure if just on my setup, but I have been getting a random "Unable to start receiver ualberta.cmput301w16t16.glamorousborrowingwhaleapp.NetworkChangeReceiver: java.lang.NullPointerException" error. Happens when the app is opened occasionally, and when a crash of different nature occurs and the app is reopened.  Suggest a try catch somewhere?

**Comment by mbaydala** [comment]
I'm not getting that error but I want to fix it, does it give a line or location or anything?

**Comment by AdamGualberta** [comment]
The next time my build crashes with that error I will post the stacktrace.

**Comment by LSouthwell** [comment]
I get this too, but it's every time I run the app. Once I press 'ok' on the error message it closes and I can open the app up just fine.

**Comment by mbaydala** [comment]
thanks, strange that it only seems to happen on some devices. I'll add a try/catch when someone posts their stack trace

**Comment by AdamGualberta** [comment]
aha I got one - here's google doc link https://docs.google.com/document/d/1J1_yzG2r5lTz071e7NdSYjp5-8vdmBwwpnvC26PjIhs/edit
