### ISSUE TITLE
Editing an item then hitting "back" auto-shows profile info pop-up.

### ISSUE THREAD

**Issue by andrewpaquette** [CMPUT301W16T16/GlamorousBorrowingWhaleApp#3]
The profile info pop-up isn't really the problem: it's not even supposed to be there (why would you want to see your own profile info in a pop-up; it's there because we have no TheirItems yet). The problem is that hitting back MUST be triggering a single click on some item in the ListView/ArrayAdapter... and why would that be?

**Comment by AdamGualberta** [comment]
Hi - I'm not understanding which pop-up: the alertdialog that appears when you long-press your info on the myProfile screen? That box is just an edit box. Please let me know if else.

**Comment by andrewpaquette** [comment]
oh, to be more specific, you need to make an item, then go in to edit that item, then hit back. it pops up the "who owns this item" dialog (ProfileView)

**Comment by AdamGualberta** [comment]
Oh I understand now - will look into this.

**Comment by AdamGualberta** [comment]
Added this comment and commented out some code:

Hi - Adam - I don't believe this popup should be here. It would be better used where the view for items that are not owned by you but being borrowed by you and the view for browsing other peoples stuff.

The reason being is it is implied that the user, you, owns an item in the MyItems view.  This popup would be great for a view in which the items are NOT owned by the user, you.

If this is good, please mark this as solved or however this thing works.

**Comment by andrewpaquette** [comment]
yeah, I concur that it should not be there (i commented on this detail in the first message of this Issue), the more troubling thing is that it's being triggered at all. anyyyyyway, let's just mark it as good and hopefully the problem doesn't return
